# Linch Mind 统一配置文件
# Session V60 重构 - 单一配置源
# 生成时间: 2025-08-03T08:00:00
# 
# 支持环境变量: ${VARIABLE_NAME:-default_value}
# 配置验证: 启动时自动验证所有配置项

app_name: "Linch Mind"
version: "0.1.0"
description: "Personal AI Life Assistant API"
debug: false

server:
  host: "0.0.0.0"
  port: 58471
  port_range: [8000, 9000]
  reload: true
  log_level: "info"

database:
  sqlite_url: ""  # 自动设置为 ~/.linch-mind/db/linch_mind.db
  chroma_persist_directory: ""  # 自动设置为 ~/.linch-mind/db/chromadb
  embedding_model: "all-MiniLM-L6-v2"
  vector_dimension: 384

connectors:
  registry_url: "${REGISTRY_URL:-http://localhost:8001/v1}"
  install_dir: "connectors/installed"
  config_dir: "connectors"
  filesystem_enabled: true
  filesystem_watch_paths: []
  clipboard_enabled: false

ai:
  default_embedding_model: "all-MiniLM-L6-v2"
  max_search_results: 10
  recommendation_threshold: 0.7
  providers: []