name: linch_mind
description: Privacy-first Personal AI Assistant

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # 状态管理
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0

  # 网络和数据 (已移除HTTP，使用IPC通信)
  # dio: ^5.3.0  # 已移除 - HTTP客户端不再需要
  # http: ^1.1.0  # 已移除 - HTTP客户端不再需要
  sqflite: ^2.3.0
  shared_preferences: ^2.2.0

  # UI组件 
  reactive_forms: ^17.0.0

  # 工具
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  file_picker: ^8.0.0+1

  # 窗口管理
  window_manager: ^0.3.7
  
  # WebView支持
  webview_flutter: ^4.4.2

  # Material Design
  material_color_utilities: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 代码生成
  build_runner: ^2.4.0
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  riverpod_generator: ^2.3.0
  
  # 代码分析
  flutter_lints: ^3.0.0
  
  # 测试工具
  mockito: ^5.4.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/