name: 🚀 Flutter Build (Simplified)

on:
  push:
    branches: [main, develop]
    paths:
      - 'ui/**'
      - '.github/workflows/flutter-build-simple.yml'
  pull_request:
    branches: [main]
    paths:
      - 'ui/**'
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.24.3"

jobs:
  build:
    name: Build Flutter App
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            build_path: build/linux/x64/release/bundle
          - os: macos-latest
            platform: macos
            build_path: build/macos/Build/Products/Release
          - os: windows-latest
            platform: windows
            build_path: build\windows\x64\runner\Release
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
      
      - name: Enable desktop support
        run: |
          flutter config --enable-${{ matrix.platform }}-desktop
      
      - name: Get dependencies
        run: |
          cd ui
          flutter pub get
      
      - name: Run tests
        run: |
          cd ui
          # Skip tests if no test directory exists
          if [ -d "test" ]; then
            flutter test
          else
            echo "No test directory found, skipping tests"
          fi
      
      - name: Build app
        run: |
          cd ui
          flutter build ${{ matrix.platform }} --release
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-${{ matrix.platform }}
          path: ui/${{ matrix.build_path }}
          retention-days: 7